import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { getMessageTest } from './api/CallApis'

export default function Home() {

    const [message, setMessage] = useState([]);

    const getNewMssage = async()=>{

        const newMessage =  await getMessageTest();
        console.log(newMessage);
        setMessage(newMessage.data);     
    }

    useEffect(()=>{
        getNewMssage();
    },[]);    

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Get Test</a>
        </h1>
        <h1>{message}</h1>

      </main>

      <footer className={styles.footer}>
        <h1>Pruebas Post</h1>
      </footer>
    </div>
  )
}
