import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { getListApi } from './api/CallApis'

export function GetListest() {

  const [getList, setGetList] = useState([]);
  
    const getNewMssage = async()=>{

        const newMessage =  await getListApi();
        console.log(newMessage);
        setGetList(newMessage.data);     
    }

    useEffect(()=>{
        getNewMssage();
    },[]);    

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">GeList Test</a>
        </h1>
        <div>

          {getList.map((list) => (
            <div key={list.Id} >{list.Nombre}</div>
          ))}

        </div>

      </main>

      <footer className={styles.footer}>
        <h1>Pruebas Post</h1>
      </footer>
    </div>
  )
}
