import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { getListApi, PostList } from './api/CallApis'
import Post from './Post'

export   function GetList() {

  
  const [getList, setGetList] = useState([]);
  
    const getNewMssage = async () => {
        const newMessage =  await getListApi();
        setGetList([...newMessage?.data]);   
    }
    

    useEffect(()=>{
        getNewMssage();
    },[getList]);    

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Get Test</a>
        </h1>
          {getList?.map((list) => (
            <div key={list?.Nombre} >{list?.Nombre}</div>
          ))}
      
      {/* {data?.map((list) => (
            <div key={list?.Nombre}> {list?.Nombre}</div>
          ))} */}
        
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
