import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import {GetListest} from './GetList'
import { getListApi, PostList } from './api/CallApis'


export default function Post() {
    const [data, setPost] = useState({

        Id:0,
        Nombre:""
    
      });
    
      const handleChange = (event) =>{
    
        const value = event.target.value
        setPost({
    
          ...data,
              [event.target.name] : value
    
        });
      }
    
      const handleSubmit = (event) => {
    
        event.preventDefault();

        const userData = {
            
        Id:Number(data.Id),
        Nombre: data.Nombre
        }

        console.log('userData',userData);  
        PostList(userData).then( async () =>{
          const getList = await getListApi();
        })
        setPost({
          Id:"",
          Nombre:""
        });


      }
      useEffect(() => {
       getListApi()
      }, [])
      
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Post Test</a>
        </h1>

        <div>Formulario
            <form onSubmit={handleSubmit}>

            <label>
                Post Title:
                <input
                type="number"
                name="Id"
                id=""
                onChange={handleChange}
                value={data.Id}
                />

                <input
                type="text"
                name="Nombre"
                id=""
                placeholder="Introduce Nombre"
                value={data.Nombre}
                onChange={handleChange}
                /> 
                <button type="submit" onClick={getListApi} >Enviar</button>
            </label>

            </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <h1>Pruebas Post</h1>
      </footer>
    </div>
  )
}
