import React, { useEffect, useState } from 'react'
import { deleteList, getListApi, PostList, UpdateList } from './api/CallApis';
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link'
export const Update = ({getAll}) => {
    const [data, setUpdate] = useState({
        Id:0,
        Nombre:""
      });
    
      const handleChange = (event) =>{
        const value = event.target.value
        setUpdate({
          ...data,
              [event.target.name] : value
        });
      }
    
      const handleSubmit = (event) => {
        event.preventDefault();
        const userData = {
            Id:Number(data.Id),
            Nombre: data.Nombre
        }
        //Reload page when action is post
        UpdateList(userData).then(async() => {
            await getAll();
        });
        //Clean Input
        setUpdate({
          Id:"",
          Nombre:""
        });
      }

  return (
    <div className={styles.container}>
    <Head>
      <title>Test React Post-Get</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <main className={styles.main}>
      <h1 className={styles.title} >   
      
      </h1>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Update</a>
      </h1>

      <div> Formulario:
          <form onSubmit={handleSubmit}>
          <label>
              Update Title:
              <input
              type="number"
              name="Id"
              id=""
              onChange={handleChange}
              value={data.Id}
              />

              <input
              type="text"
              name="Nombre"
              id=""
              placeholder="Introduce Nombre"
              value={data.Nombre}
              onChange={handleChange}
              /> 
              <button type="submit"   >Enviar</button>
          </label>
          </form>
      </div>
    </main>

    <footer className={styles.footer}>
      {/* <h1>Pruebas Post</h1> */}
    </footer>
  </div>
  )
}
